source "https://cdn.cocoapods.org/"
platform :ios, '14.0'
workspace "ios"

# Comment this line if you're not using Swift and don't want to use dynamic frameworks.
use_frameworks!

target 'ios' do
  project 'ios'

  pod "MultiplatformLocaleGooglePlayStore", :path => "../multiplatform-locale-google-play-store"
end
